# Generated by Django 5.1.6 on 2025-02-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_alter_modifications_cake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='variables_of_modifications',
            field=models.ManyToManyField(blank=True, related_name='orders', to='cakes.variablesofmodification'),
        ),
    ]
