# Generated by Django 5.1.6 on 2025-02-27 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0003_alter_order_variables_of_modifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cakes.cake'),
        ),
        migrations.AlterField(
            model_name='order',
            name='variables_of_modifications',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='cakes.variablesofmodification'),
        ),
        migrations.AlterField(
            model_name='variablesofmodification',
            name='modification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables_of_modification', to='cakes.modifications'),
        ),
    ]
