# Generated by Django 5.1.6 on 2025-03-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0005_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='variables_of_modifications',
        ),
        migrations.AddField(
            model_name='order',
            name='variables_of_modifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
